### PR TITLE
Full translation

### PR DESCRIPTION
**Pull request by martinheidegger**
Full translation of the learnyounode based on the translation efforts of workshopper and workshopper-exercise

### CODE REVIEW

**Comment by rvagg** [comment]
Added people listed here as collaborators:

* Takashi Fujita @tgfjt
* Ryuta Nakashima @AtuyL
* Leigh Zhu @lisposter
* Toshiharu Harada @haradats

Please be sure to tend to your language sections, pull requests are always coming in to change minor wording and it would be great to have them always updated.

Also please be sure to pull-request all your changes, even minor ones that you merge immediately. It helps with visibility. Also allow for dissention, so leave non-trivial pull-requests open for at least a day for discussion.

**Comment by tgfjt** [comment]
@rvagg 
Thank you! I got the point.

**Comment by lisposter** [comment]
@rvagg 

Thank you, I will try my best.

**Comment by rvagg** [comment]
this is in npm as 2.0.0, please install and test, I'm quite out of my depth here with these new languages

**Comment by tgfjt** [comment]
@rvagg 
I commited this:
https://github.com/rvagg/learnyounode/commit/87588b8017c110a1d119361e5e309d364878e024

**Pull request merged**
