### PR TITLE
upate collaborators

### PR DESCRIPTION
**Pull request by leonascimento**
@ralphtheninja ok?

### CODE REVIEW

**Comment by sidorares** [comment]
@leonascimento as @ralphtheninja mentioned instead of closing #206 and reopening new one  you could do `rebase -i HEAD^3` in your local branch, force push to github and PR would reflect updated rewritten history

**Comment by leonascimento** [comment]
thanks @sidorares!

**Comment by sidorares** [comment]
no problems! I remember I was scared doing interactive rebase and it turned out it's actually very easy to do. Now it's part of my workflow - before pushing the code, look through commit messages, squash related and delete "add debug output" "delete debug output" pairs :)

**Comment by julianduque** [comment]
@sidorares great stuff :), so this could be a good opportunity to put that into work and update the commit message to something more meaningful, like `add @leonascimiento to collaborators` :)

**Comment by ralphtheninja** [comment]
Yep. But this time since it's just a single commit it should be enough to amend it:

```
$ git commit --amend -m 'add @leonascimiento to collaborators'
$ git push -f
```

**Pull request closed without merging**
