### PR TITLE
[zh-cn] improve some texts for more clearly

### PR DESCRIPTION
**Pull request by lisposter**
I have rewrite some text in Chinese, make it more easy to read. LGTM, ping @rvagg,  please make a minor release.

### CODE REVIEW

**Comment by rvagg** [comment]
do we have anyone else in the repo to review this?

**Comment by lisposter** [comment]
@rvagg I don't know, maybe not. did you means I can merge it by myself if it lgtm? I'm not  sure.

**Comment by rvagg** [comment]
@lisposter if we have nobody else here who can review zn-cn then go ahead and merge, just let me know if you want a release with the changes

**Comment by lisposter** [comment]
@rvagg OK, merged. Please Make a release when it's convenient.

**Comment by rvagg** [comment]
2.2.2, thanks @lisposter!

**Pull request merged**
