### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### rvagg/learnyounode now has a Chat Room on Gitter

@ralphtheninja has just created a chat room. You can visit it here: [https://gitter.im/rvagg/learnyounode](https://gitter.im/rvagg/learnyounode?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/rvagg/learnyounode?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Just had to try out the PR feature in gitter. Seems to work pretty well :)

**Comment by ralphtheninja** [comment]
Is anyone against having a gitter badge in the README? I think sometimes it's easier to hit people up in an ad hoc chat when explaining things. Github issues might be good for discussing code but not always ideal when explaning.

**Comment by ralphtheninja** [comment]
FYI, I opted out from future automatic PRs from gitter.

**Comment by rvagg** [comment]
FTR I +1ed this on IRC already

**Comment by Flet** [comment]
This is a nice idea :)

Is it possible to share the same gitter instance with the nodeschool discussions repo? A lot of issues here are more general user/environment versus bugs, and there may he a wider audience of helpers in the nodeschool chat.

**Comment by ralphtheninja** [comment]
@Flet Hmm I don't know. Worst case scenario is creating a new gitter instance and linking to that as well.

**Comment by Flet** [comment]
Indeed, fine with it either way. I just know there are quite a few folks who idle in that nodeschool chat who are happy to help.

**Comment by ralphtheninja** [comment]
@Flet What's the name of that channel?

**Comment by Flet** [comment]
https://gitter.im/nodeschool/discussions

**Comment by ralphtheninja** [comment]
@Flet I totally misunderstood you before. Much better to use the same room. Updating PR.

**Pull request closed without merging**
