### PR TITLE
Updating collaborators on package.json

### PR DESCRIPTION
**Pull request by lucasfcosta**
Sorry for all these pull requests, I just thought it would be easier to fix this if I just did it again after pulling from the upstream/master.
I will make sure to study about git's rebase tool as soon as I get home.

### CODE REVIEW

**Comment by ralphtheninja** [comment]
You don't have to create new pull requests. You can use the same PR and `git push -f` on your master and the PR will update automatically.

**Comment by ralphtheninja** [comment]
What I generally do is

```
$ git fetch upstream
$ git rebase upstream/master
$ git push -f
```

**Comment by lucasfcosta** [comment]
The PRs were closed automatically, that's why I had to create others.
I think this will be the last one, it looks like everything is all right.
Thanks for the information about rebases!

**Comment by ralphtheninja** [comment]
Hmm why would they be closed automatically? Is that because of the tool you are using? Not questioning, just curious.

**Comment by lucasfcosta** [comment]
I'm not at home, I'm using the git shell on Windows, this may be the reason the PR's keep being closed automatically.
I've also fixed the indentation.

**Comment by ralphtheninja** [comment]
It's on journeys like that you learn something :)

**Comment by lucasfcosta** [comment]
Yes, I've learned a lot! Thanks for the tips!

**Pull request merged**
