### PR TITLE
Update problem.es.md

### PR DESCRIPTION
**Pull request by pierregermain**
only some changes in spanish but should be improved more.

### CODE REVIEW

**Comment by rvagg** [comment]
need a reviewer for this, @julianduque perhaps?

**Comment by julianduque** [comment]
@rvagg @pierregermain only that minor change, otherwise LGTM

**Comment by rvagg** [comment]
ping @julianduque & @pierregermain, can we get this sorted?

**Comment by julianduque** [comment]
@rvagg fixed, merged and closed :)

**Pull request merged**
