### PR TITLE
Added explicit instruction about test file

### PR DESCRIPTION
**Pull request by RichardLitt**
I've seen this twice: a beginner makes their own test file to test their
code that checks the line length of a file, and then is confused when
the tests fail. I think this line is a bit confusing - it would be better
to add in something that tells the user they don't need to make their
own file, just to help readers who don't read this line too much.

### CODE REVIEW

**Comment by martinheidegger** [comment]
Clumsy japanese translation: ”自分でテスト用のファイル作る必要がありません。"
spanish? chinese?

**Comment by tgfjt** [comment]
@martinheidegger 
How about this?: "テスト用のファイルを作る必要はありません。"

**Comment by martinheidegger** [comment]
@tgfjt thx.

**Comment by RichardLitt** [comment]
Want me to put that in here, or wait for a PR if this gets merged?

**Comment by martinheidegger** [comment]
@RichardLitt Please add it. Unless its a english bug it makes sense to add translations for improvements too.

**Comment by rvagg** [comment]
@RichardLitt this should probably go in my_first_io/problem.md rather than my_first_async_io/problem.md

I'm tempted to say that it doesn't even belong in there because it's in "BABY STEPS" that we first introduce the concept of being passed in test arguments and not having to provide your own. Perhaps a compromise approach would be to put a similar message in baby_steps/problem.md.

Thoughts from other collaborators?

**Comment by rvagg** [comment]
> @RichardLitt this should probably go in my_first_io/problem.md rather than my_first_async_io/problem.md

I meant to say that it's in "MY FIRST I/O!" where you first encounter a test file being passed in, and "MY FIRST ASYNC I/O!" is simply an extension of this exercise.

**Comment by RichardLitt** [comment]
I added it to _My First I/O!_. I still think it should be explicitly stated - although the users know what arguments are, I've still seen this stump beginners. I don't think they're expecting arguments that are the file name to be passed in. I know it seems like overkill, but it might help in general if there is just this gentle nudge. The mistaken idea that you should make your own test file happened today at Node Summit and happened (to me, actually) at Node School on Saturday.

**Comment by rvagg** [comment]
There's been quite a number of similar issues over time wanting to add repeated explicit instructions to problem text. The biggest problem though is that _people don't read stuff_, so you have to optimise for the smallest chunk of text possible to get them going. The rule we've adopted so far with learnyounode is to say it once and don't repeat it. So -1 to adding it to both of these exercises, there's a limit to the handholding we can and should do.

**Comment by RichardLitt** [comment]
Noted. Removed from _My First Async I/O_. Agreed about the lack of reading.

**Comment by rvagg** [comment]
@julianduque
@martinheidegger
@ClimbsRocks
@tgfjt
@AtuyL
@lisposter
@haradats
@a0viedo
@lucasfcosta
@ericdouglas
@leonascimento
@isRuslan
@tdd
@gorhgorh

New wording going in to _en_, please take care of your translations.

**Comment by tdd** [comment]
Done, see PR.

-- 
Christophe Porteneuve
tdd@tddsworld.com

**Pull request merged**
