### PR TITLE
update language files of zh-cn

### PR DESCRIPTION
**Pull request by lisposter**
Make some update for Simplified Chinese. I am not sure whether the title is cool enough or not, others change are LGTM.

### CODE REVIEW

**Comment by lisposter** [comment]
@rvagg I think, these three modules are all ready, and then, `learnyounode` will has a full translation of Simplified Chinese.  :beers:

**Comment by rvagg** [comment]
ok, let's do this, I'll minor bump and release them all right now so it'll be learnyounode@2.1.0 shortly.

**Comment by rvagg** [comment]
all done, thanks very much, keep an eye on here for problems related to zh-cn!

**Comment by lisposter** [comment]
@rvagg cool!  I have watched this repo, will do my best for it.

**Pull request merged**
