### PR TITLE
Adding pt-br translation files

### PR DESCRIPTION
**Pull request by lucasfcosta**
Hello, we have done a brazilian portuguese translation, we hope you like it.
In case you want to see more details about our work, this is the link to our repository https://github.com/lucasfcosta/learnyounode-pt-br

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@diasdavid @pgte Does this look ok? :)

**Comment by rvagg** [comment]
as per @ralphtheninja's comment, it would be good to get sign-off from some other native pt-br speakers (helpful if we know them!), if it's all good then we'll merge and add you as a collaborator.

**Comment by lucasfcosta** [comment]
Hi @rvagg, it would be unfair to add only me as a collaborator because this work has been done by many people, you can credit us all under any other collective group name if you want to.
Thanks!

**Comment by rvagg** [comment]
@lucasfcosta where can I see that list? I'd love to be able to add >1 people to the repo to manage pt-br if they have already contributed non-trivial amounts of work to what's in this PR.

**Comment by lucasfcosta** [comment]
We've organized [our Issue Tracker](https://github.com/lucasfcosta/learnyounode-pt-br/issues) creating one issue for each chapter. I was seeing it and I've also counted how many chapters each one of us has translated (LOL, I thought more people contributed, sorry).

This is the list of everyone that contributed translating exercises and how many exercises (or files) they've translated:
[Lucas Fernandes da Costa](https://github.com/lucasfcosta) - 8 Exercises (+ credits, help and pt-br.json)
[Eric Douglas](https://github.com/ericdouglas) - 4 Exercises
[Leo Nascimento](https://github.com/leonascimento) - 1 Exercise

Some guys were also translating the three documentation files included on this project, but I think you won't use them.

**Comment by rvagg** [comment]
OK, good to know there's a few of you. I've added you all as collaborators. If you think this is good to merge and you've tested the result of it then go ahead and merge it.

Let me know when it's ready for a release and I'll bump minor and get it out!

Thanks!

**Comment by lucasfcosta** [comment]
I will test it and review the translation files this week and merge it as soon as possible!
Thanks!

**Comment by rvagg** [comment]
good for release @lucasfcosta?

**Comment by lucasfcosta** [comment]
Yes, @rvagg , I've just tested it here and fixed a filename which I've forgotten.
I think it's good for release.

I will be translating the workshopper module soon so the brazilian users can have a fully translated interface.

**Comment by rvagg** [comment]
published as 2.3.0, thanks for the good work here!

**Comment by lucasfcosta** [comment]
You're welcome! I'm glad for being able to contribute in such an awesome project

**Comment by diasdavid** [comment]
Oh, my apologies, I missed this thread entirely. I can definitely read and understand PT-BR, but I would not be the best person to validate it (there is a difference between PT-PT and PT-BR). I'm sure @tdantas or @qmx can help! :)

**Comment by pgte** [comment]
What @diasdavid said.
BTW, a pt-pt release based off this one would also be cool, but don't know if the small difference justifies it :)

**Pull request merged**
