### PR TITLE
updating collaborators on package.json

### PR DESCRIPTION
**Pull request by lucasfcosta**
Well, I messed up my fork of the repository so I thought it would be better to roll it back and open a new pull-request.
Here it is @ralphtheninja , sorry for the mess

### CODE REVIEW

**Comment by ralphtheninja** [comment]
Sorry to bug you again. Mind rebasing it on latest master? I can do it for you if you don't have time.

**Comment by lucasfcosta** [comment]
No problem @ralphtheninja , I'm new to Git and I need to learn some good practices, thanks for your advice. I hope everything works now.

**Comment by ralphtheninja** [comment]
@lucasfcosta This commit doesn't look right https://github.com/lucasfcosta/learnyounode/commit/17b81ba2b80e05392d844e5e043c7f139c3feabd

**Comment by ralphtheninja** [comment]
@lucasfcosta Remember that as long as this has not been merged you can force push as much as you want to your own master.

**Pull request closed without merging**
