### PR TITLE
update node docs to v0.10.35

### PR DESCRIPTION
**Pull request by ClimbsRocks**
As raised in Issue 167, the node docs in this project were last updated over a year ago, so I updated to the most recent version. 

The structure is exactly the same, and each file name is the same as it was a year ago. All existing links in the project should continue to work, the files they point to will now hold the updated docs. 

The only thing I added was two logo images for offline viewing. 

I tested all files while my computer was offline, and all of them work as expected. 

This project has been a great resource for me, so I'm happy to have the chance to contribute something in return! Let me know if there's anything else I can do to help with this. 

Thanks,
preston

### CODE REVIEW

**Comment by rvagg** [comment]
:+1: from me, anybody else got time to actually look at these in offline mode to see how well they work as-is?

**Comment by martinheidegger** [comment]
Checked it out, read it offline. LGTM

**Comment by rvagg** [comment]
added @ClimbsRocks as collaborator, will merge this and release as a patch version

**Comment by rvagg** [comment]
1.0.7

**Pull request merged**
